version: '2'
services:
    sshd:
        restart: always
        build: ./sshd
        ports:
            - "2001:22"
    nginx:
        restart: always
        build: ./nginx
        networks:
            - mainnet
        links:
            - app
        volumes:
            - ./nginx:/usr/share/nginx/html
        ports:
            - "80:8080"
    app:
        restart: always
        build: ./app
        networks:
            - mainnet
        volumes:
          - ./app:/usr/src/app
        depends_on:
          - sshd
networks:
    mainnet:
